# -*- coding: utf-8 -*-
"""Grade_by_Average_calculator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12_CEyJ4rRDYuZ_5nxE1tK8aFEI2ODsDI
"""

#create a function that can calculate the average
def average_calculator(marks):
    sum_of_marks = sum(marks)
    length_of_marks = len(marks)
    result = sum_of_marks / length_of_marks
    return result

marks_input = input("input marks hier (comma separated): \n")
marks_list = [int(mark) for mark in marks_input.split(",")]

result = average_calculator(marks_list)
print("your average is:", result)

if result >= 90 or result == 100:
  print("Grade: A")
elif result >= 80 :
  print("Grade: B")
elif result >= 70 :
  print("Grade: C")
elif result >= 60:
  print("Grade: D")
elif result > 100 or result < 0:
  print("Error, the average must be between 0-100")
else:
  print("Grade: E")